### ISSUE TITLE
.Net Core on Linux

### ISSUE THREAD

**Issue by hspeedy** [VahidN/EPPlus.Core#1]
Thanks for porting EPPlus to .Net Core! Great job! But I have encountered a little
problem while testing on linux. One of it's dependencies seems to rely on on gdi32+
and so it doesn't load on linux.

**Comment by VahidN** [comment]
Hi, Thanks. 
After installing the `libgdiplus` I could run the functional tests on Ubuntu
[More info](https://github.com/CoreCompat/CoreCompat/issues/3)

```
sudo apt-get update
sudo apt-get install libgdiplus
```

![vba](https://cloud.githubusercontent.com/assets/766010/20399005/b18c2896-ad04-11e6-90ba-b92908061550.png)

Failed tests are `VBA` related, because .NET Core lacks some of the encryption Algorithms.

**Comment by hspeedy** [comment]
Thanks for helping me. After installing libgduplus everything works fine. I'm using Linux Mint 18.

**Comment by kinglionsoft** [comment]
On Ubuntu 16.04, with installing libgduplus, it works fine. But on CentOS 7, after installing libgdiplus, it still can not load 'gdiplus' when I call 'AutoFitColumns()':  
```
Error: The type initializer for 'System.Drawing.GDIPlus' threw an exception.
-->The type initializer for 'System.Drawing.GDIPlus' threw an exception.
-->Unable to load DLL 'gdiplus': The specified module could not be found.
```
By the way, gdipus is:
```bash
libgdiplus-2.10-9.el7.x86_64
```

I do not know how to fix it, just simply skip calling 'AutoFitColumns()'  to avoid this error:

**Comment by VahidN** [comment]
`libgdiplus` is part of the Mono project and you can find more info about how to resolve `DllNotFoundException` here:
- [DllNotFoundException](http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/)
- [Problem: GDIPlusInit](http://www.mono-project.com/docs/gui/problemgdiplusinit/)

**Comment by kinglionsoft** [comment]
Thanks for reply.

**Comment by drwharris** [comment]
I ran into this using VS2017 with docker integration. Solution was to add the following to my dockerfile

    FROM microsoft/aspnetcore:2.0 
    ARG source
    RUN apt-get update                      #Add this line
    RUN apt-get install -y libgdiplus   #Add this line

**Comment by yberstad** [comment]
Thanks for helping out with this!
I'm running on macOS, and I had to run the following command to get it to work:
`brew install mono-libgdiplus`
