### ISSUE TITLE
No need to define net45 and net46 frameworks.

### ISSUE THREAD

**Issue by StefH** [VahidN/EPPlus.Core#10]
`<TargetFrameworks>net40;net45;net46;netstandard1.3</TargetFrameworks>`

can be changed into

`<TargetFrameworks>net40;netstandard1.3</TargetFrameworks>`

Always target only the lowest framework which will work.

And is netstandard1.3 the lowest you can go?

**Comment by VahidN** [comment]
- True, But maybe someone is targeting net45 and wants a net45 .dll! (Having it is not very important)
- Yes, Its System.Darwing's dependency uses netstandard1.3.

**Comment by StefH** [comment]
When someone creates a net45 project, your library can be easily used if it targets net40 (nuget dependencies work that work).

For referenence, take a look at some common projects like newtonsoft.json
