### ISSUE TITLE
Not working in .net Core 2.0

### ISSUE THREAD

**Issue by gbfromhb** [VahidN/EPPlus.Core#13]
It looks like there are some conflicts with .net Core 2.0. I'm guessing that maybe recompiling this with the CoreCompat.System.Drawing.v2 replacing the CoreCompat.System.Drawing might do it, but I would not put any money on it. Right now it looks like this might be the only thing holding me up from moving a project to .net core 2.0. Just wanting to know if you have any plans of checking into this. Thanks for all the work you have done. Looking forward to hearing from you.

**Comment by VahidN** [comment]
Added initial netstandard2.0-preview1 support via https://github.com/VahidN/EPPlus.Core/commit/0b22e943205a42c13c0fa8a8581ee5b84953fd42, also [its NuGet package](https://www.nuget.org/packages/EPPlus.Core) has been updated too.

**Comment by gbfromhb** [comment]
That is awesome, thank you for the response.
