### ISSUE TITLE
Amend ShowDataAs function

### ISSUE THREAD

**Issue by GeorgeGrainger** [VahidN/EPPlus.Core#14]
Within the ExcelPivotTableDataField.cs the `ShowDataAs` function is commented out, thus, this functionality is unavailable

**Comment by VahidN** [comment]
Yes. It's the same as [the original one here](http://epplus.codeplex.com/SourceControl/latest#EPPlus/Table/PivotTable/ExcelPivotTableDataField.cs). The purpose of this library is not to change that (or anything else). You can ask this from the original authors of the epplus [here](http://epplus.codeplex.com/workitem/list/basic).
