### ISSUE TITLE
The type initializer for 'System.Drawing.GDIPlus' threw an exception

### ISSUE THREAD

**Issue by RustamIbragimov** [VahidN/EPPlus.Core#16]
When I create simple worksheet without formatting everything works fine. But, as long as I try to add some style or format cells it throws `The type initializer for 'System.Drawing.GDIPlus' threw an exception`. 
This is a part of exception stack
`at System.Drawing.GDIPlus.GdipGetGenericFontFamilySansSerif(IntPtr& fontFamily)\n   at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)\n   at System.Drawing.FontFamily.get_GenericSansSerif()\n   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)\n   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)\n   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)\n   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)\n   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()\n`

The code I am trying to execute are `worksheet.Cells[1, 1, 4, 5].AutoFitColumns();` and any other formatting. 

I am using .NET Core 1.1. Mac OS Sierra.

**Comment by VahidN** [comment]
You need to install the `GDIPlus` dependencies too. [more info](https://github.com/CoreCompat/CoreCompat/issues/3#issuecomment-277347158)

**Comment by ikumshyamal** [comment]
After installing 'gdiplus' do this...

https://en.code-bude.net/2017/05/08/net-core-gdiplus-dll-not-found-in-linux/comment-page-1/#comment-119157
