### ISSUE TITLE
.Net Core 2.0 Not Working

### ISSUE THREAD

**Issue by dvlkv** [VahidN/EPPlus.Core#17]
[CS0012] The type 'Image' is defined in an assembly that is not referenced. You must add a reference to assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

My Code is:
```
worksheet.HeaderFooter.OddFooter.InsertPicture(new FileInfo("Images/docWatermark.png"), PictureAlignment.Right);
```
.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.7.2" />
    <PackageReference Include="EPPlus.Core" Version="1.5.2" />
    <PackageReference Include="iTextSharp.LGPLv2.Core" Version="1.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0-preview2-final" />
    <PackageReference Include="OpenXMLPowerTools.Core" Version="1.0.0" />
  </ItemGroup>
</Project>
```

**Comment by VahidN** [comment]
Ignore that warning in VSCode or other editors. [The compiled program works (tested and it produces the expected .xlsx file)](https://github.com/VahidN/EPPlus.Core/blob/master/src/EPPlus.Core.SampleWebApp/Controllers/HomeController.cs#L144). `v1.5.2` for `netstandard2.0` uses `CoreCompat.System.Drawing.**v2**` and not `CoreCompat.System.Drawing`.

**Comment by dvlkv** [comment]
It's a compiler error. I can't ignore it. It worked while i was using netstandard1.6

**Comment by VahidN** [comment]
- [Update your .NET Core SDK](https://www.microsoft.com/net/download/core#/sdk). 
- Update your dependencies. It seems you are still using the `preview` versions.
- If you have old dependencies which are using `CoreCompat.System.Drawing`, you should update them too. The new dependency for them is `CoreCompat.System.Drawing.**v2**`.
- Remove `TreatWarningsAsErrors`.
- Now try again: (it works, and tested)
![build](https://user-images.githubusercontent.com/766010/29396670-639fdcda-832e-11e7-97a9-318283b20bcd.png)

**Comment by dvlkv** [comment]
Fixed it clearing packages by this:
`dotnet nuget locals all --clear`
Thank you
