### ISSUE TITLE
.NET Core 2.0 System.Drawing

### ISSUE THREAD

**Issue by Nohinn** [VahidN/EPPlus.Core#18]
Hello, right now this project makes use of CoreCompat lib to get the System.Drawing functionalities...

Could it be possible to use the official ones (System.Drawing.Common + System.Drawing.Primitives) from https://dotnet.myget.org/F/dotnet-core/api/v3/index.json?

The links to both packages are:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Drawing.Primitives
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Drawing.Common

**Comment by VahidN** [comment]
Great! let's wait until it's final.

**Comment by VahidN** [comment]
Also this project is now part the original project as a new branch:
![branch_core](https://user-images.githubusercontent.com/766010/29571084-856427a2-876d-11e7-83ae-ef9515f0d514.png)
More info [here](http://epplus.codeplex.com/SourceControl/changeset/c92b52a9e204) and [here](http://epplus.codeplex.com/workitem/list/basic?field=CreationDate&direction=Descending&issuesToDisplay=Open&keywords=.net%20core&emailSubscribedItemsOnly=false).

**Comment by VahidN** [comment]
The original project has been moved to Github
https://github.com/JanKallman/EPPlus/commits/master
And there will be an official beta with support for .NET Core, stable version will probably await Microsoft releasing System.Drawing in .NET Core.

**Comment by VahidN** [comment]
The first beta version of the `System.Drawing.Common`  has been released:
https://www.nuget.org/packages/System.Drawing.Common 

But I can't use it from a .NET Standard project:
 error NU1202: Package System.Drawing.Common 4.5.0-preview1-25718-03 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Drawing.Common 4.5.0-preview1-25718-03 supports: **netcoreapp2.0** (.NETCoreApp,Version=v2.0)

**Comment by VahidN** [comment]
Added via #https://github.com/VahidN/EPPlus.Core/commit/99af3ef4e0b71ab20b093665ca32accfcbaaa480
```
dotnet add package EPPlus.Core --version 1.5.3 
```
