### ISSUE TITLE
Object must implement IConvertible.

### ISSUE THREAD

**Issue by thecobe** [VahidN/EPPlus.Core#21]
Hi
i have this error on package.SaveAs "System.InvalidCastException: 'Object must implement IConvertible.'
" with nuget package EPPlus.Core 1.52
the strange thing is that it works fine if i attached project EPPlus.Core to solution
how it is possibile?? aren't the same?

**Comment by VahidN** [comment]
I can't reproduce it. I added a new console sample called [NugetPackageTest](https://github.com/VahidN/EPPlus.Core/tree/master/src/NugetPackageTest). It just uses the [EPPlus.Core's nuget package](https://github.com/VahidN/EPPlus.Core/blob/master/src/NugetPackageTest/NugetPackageTest.csproj#L7) and it has no dependency on the other sources. It works fine and creates the report.xlsx file.
