### ISSUE TITLE
At Save doesn't recognize format

### ISSUE THREAD

**Issue by bwsolutionsti** [VahidN/EPPlus.Core#22]
Hi, When i want to save Excel template with EMF, doesn't recognize the type and crash the application. The format code is

ImageFormatEMF 
B96B3CAC-0728-11D3-9D7B-0000F81EF32E
Indicates the Enhanced Metafile (EMF) format.

Please!!!

**Comment by VahidN** [comment]
> This behavior occurs because the GDI+ component of the .NET Framework does not have an encoder that you can use to save files as .wmf or .emf files.
https://msdn.microsoft.com/en-us/library/ktx83wah.aspx
