### ISSUE TITLE
Is Epplus going to be shutdown?

### ISSUE THREAD

**Issue by haison8x** [VahidN/EPPlus.Core#24]
Excuse me!

I shouldn't post this question here but I don't know where it should be.

There is no update of Epplus for a very long time. Is Epplus still being maintained? Does anybody have that information?

**Comment by VahidN** [comment]
Yes. Just look at its commits history
http://epplus.codeplex.com/SourceControl/list/changesets

**Comment by VahidN** [comment]
Also they have moved to Github
https://github.com/JanKallman/EPPlus/commits/master
