### ISSUE TITLE
Cannot Read Worksheet Data

### ISSUE THREAD

**Issue by maxvt0** [VahidN/EPPlus.Core#26]
Hi, I was trying to Use this library for Reading data from xlsx files and storing them into database.
I faced issue that any kind of Excell file that i tried to read returned empty Count of Worksheets (Worksheet position out of range).

My code is simple Console application:
```csharp
using System;
 using System.IO;
 using System.Text;
 using OfficeOpenXml;

 namespace Mb.XlsxParseConsole
 {
    class Program
    {
        static void Main(string[] args)
        {
            string sFilename = "../../Data/_test_data.xls";
            FileInfo file = new FileInfo(sFilename);

            try {
                using (ExcelPackage package = new ExcelPackage(file)) 
                {
                    StringBuilder sb = new StringBuilder();
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                    int rowCount = worksheet.Dimension.Rows;
                    int colCount = worksheet.Dimension.Columns;
                    bool bHeaderRow = true;

                    for (int row = 1; row <= rowCount; row++) {
                        for (int col = 1; col <= colCount; col++) {
                            if (bHeaderRow) {
                                sb.Append(worksheet.Cells[row, col].Value.ToString() + "\t");
                            } else {
                                sb.Append(worksheet.Cells[row, col].Value.ToString() + "\t");
                            }
                        }

                        sb.Append(Environment.NewLine);
                    }

                    System.Console.Write(sb.ToString());
                }
            } catch (Exception ex) {
                System.Console.WriteLine(ex.Message);
            }


        }
    }
 }
```

I tried with multiple Excell files but i was unable to read any of them.
Any suggestions ?

**Comment by TGills** [comment]
Out of curiosity, try:

`sb.Append((worksheet.Cells[row, col].Value).ToString() + "\t");`

Just added brackets around where you are getting the value. Other than that, that's how I've been reading data from cells.

Also, I have my worksheet set to 1 instead of 0:
```
// get the first worksheet in the workbook
ExcelWorksheet worksheet = xlPackage.Workbook.Worksheets[1];
```


Here's one line from my project where I look at column 5, which holds the item type, and then assign the value in the cell to a variable:
`itemType = (worksheet.Cells[i, 5].Value).ToString(); //Column 5 = itemType`

**Comment by VahidN** [comment]
As @TGills mentioned, This is how you should access worksheets in EPPlus and Excel
```csharp
var firstWorksheet = package.Workbook.Worksheets[1]; // This should be 1 not 0
// OR
var firstWorksheet = package.Workbook.Worksheets.First();
// OR
var someWorksheet = package.Workbook.Worksheets["Sheet1"];
```

**Comment by maxvt0** [comment]
@VahidN  @TGills 

Thanks for response. But my issue is that 
`package.Workbook.Worksheets` 
is empty on each file i loaded. I can see it through debugger. 
And I tried with .xls / .xlsx  files created with Open office as well as one created with microsoft Excell

example Here.
[_test_data.xlsx](https://github.com/VahidN/EPPlus.Core/files/1328337/_test_data.xlsx)


I am using netcoreapp1.1

**Comment by VahidN** [comment]
Your file cannot be opened with MS Excel 2016.

**Comment by VahidN** [comment]
This is the structure of your file (open it with [7-zip](http://www.7-zip.org/download.html))
![xl02](https://user-images.githubusercontent.com/766010/30794124-46722ad2-a1d3-11e7-95fa-cc927f23907c.png)
And this is the structure of the new .xlsx format
![xl01](https://user-images.githubusercontent.com/766010/30794142-61e9982c-a1d3-11e7-80ef-d6eb33e2cbc5.png)

**Comment by maxvt0** [comment]
@VahidN 
So i cannot work with OpenOffice files right ?

**Comment by maxvt0** [comment]
@VahidN 
I Got this one and it still does not work
[__test_data.xlsx](https://github.com/VahidN/EPPlus.Core/files/1328363/__test_data.xlsx)

**Comment by VahidN** [comment]
There is no problem here
![xl03](https://user-images.githubusercontent.com/766010/30794747-e4d64868-a1d6-11e7-940a-4b02b9e90257.png)
[Tested with File Upload sample](https://github.com/VahidN/EPPlus.Core/blob/master/src/EPPlus.Core.SampleWebApp/Controllers/HomeController.cs#L76).

**Comment by tschlarman** [comment]
I have the same problem in a UWP library. I was just trying to enumerate the worksheets in a xlsx workbook, but the count of worksheets is 0 and there is a single worksheet in the file. Similar code works fine in a .net framework app. 

```
    List<string> tables = new List<string>();
    FileInfo fi = new System.IO.FileInfo(_fileName);
    using (var package = new ExcelPackage(fi))
    {
        foreach (var table in package.Workbook.Worksheets)
	{
		tables.Add(table.Name);
	}
    }
```

[18550116-Daily Express & Herald List of Letters.xlsx](https://github.com/VahidN/EPPlus.Core/files/2498424/18550116-Daily.Express.Herald.List.of.Letters.xlsx)
