### ISSUE TITLE
Question for ongoing development of EPPlus.Core

### ISSUE THREAD

**Issue by LiangZugeng** [VahidN/EPPlus.Core#30]
First, I want to express my thankfulness to Vahid Nasiri, EPPlus.Core is a great library and we have been using it in our projects since this Jan, it helped us reduce our dev efforts tremendously.

I noticed that EPPlus added support to .NET Core 2.0 since its 4.1.0 version although the commit comments stated that it's not fully tested, I guess moving to .NET Standard is a way EPPlus would go so both .NET Framework and .NET Core can use the library but I'm not the author so that's my guessing anyway.

I am curious for the ongoing roadmap of EPPlus.Core, what's the plan? Will EPPlus.Core be discontinued some day and Vahid Nasiri contributes on EPPlus project or EPPlus.Core will be a long-term but separate project.

We are planning for tech upgrade from current .NET 1.1 to 2.0, any information on the EPPlus.Core roadmap will be helpful. Thanks.

**Comment by VahidN** [comment]
The job is done. Also EPPlus.Core [supports .NET Standard 2.0](https://www.nuget.org/packages/EPPlus.Core/) too. So you can use it in your tech upgrades.
