### ISSUE TITLE
Upload Excel file details to Table

### ISSUE THREAD

**Issue by deanilvincent** [VahidN/EPPlus.Core#32]
Good day @VahidN By the way thank you for this helpful package. I'm currently using this package in exporting details from my table. But I'm having some difficulties on how to upload the excel details to my table. Is there a way how to get the details from excel and then upload them in the table?

I'm currently using asp.net core. I hope you have sample for that. Thank you in advance.

**Comment by VahidN** [comment]
- [How to upload](https://github.com/VahidN/EPPlus.Core/blob/master/src/EPPlus.Core.SampleWebApp/Controllers/HomeController.cs#L76)
- [How to read](https://github.com/VahidN/EPPlus.Core/blob/master/src/EPPlus.Core.SampleWebApp/Controllers/HomeController.cs#L103)
