### ISSUE TITLE
Get/Set Excel Rows Indexes

### ISSUE THREAD

**Issue by bcalcas** [VahidN/EPPlus.Core#33]
Hi!
Is there a way to get the row's index so we can use it as PK?
In your example you have the attribute ID, but how can you associate it with the row's index?

**Comment by VahidN** [comment]
[readExcelPackageToString](https://github.com/VahidN/EPPlus.Core/blob/master/src/EPPlus.Core.SampleWebApp/Controllers/HomeController.cs#L103) method shows you how to access indexes and values.
