### ISSUE TITLE
DataTable is not compatible with ASP.NET Core 1.0

### ISSUE THREAD

**Issue by mojohub** [VahidN/EPPlus.Core#4]
I have tried using this package in VS2015 (installed from NuGet) but with the following line of code...

`DataTable dataTable = new DataTable();`

I get compile error...

> DataTable does not contain a constructor that takes 0 arguments

Not that i have `using System.Data;` imported at the top of my class. What could be the problem?

**Comment by VahidN** [comment]
[DataTable](https://github.com/dotnet/corefx/issues/8622) is not supported by .NET Core 1.0 and its class is just empty. They are adding its related classes to the next version of the .NET Core:
[More info](https://github.com/dotnet/corefx/pull/12426)
