### ISSUE TITLE
EPPlus.Core, Persian(B Fonts) Font Family Not Affected

### ISSUE THREAD

**Issue by MehrdadKowsari** [VahidN/EPPlus.Core#47]
# Summary of the issue
The problem is that when I download the file and open it on Excel 2016, the font family not affected but on the font name box, it appears. If I focus on the combo box and press Enter, the font family will be affected.
How can I solve this problem ?

## Environment

```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2015)
```

## Example code/Steps to reproduce:

```
worksheet.Row(rowIndex).Style.Font.SetFromFont(new Font("B Nazanin", 14, FontStyle.Regular | FontStyle.Regular));
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
- You should start using the original library. [It has been updated to support .NET Core too](https://github.com/VahidN/EPPlus.Core/issues/37).
- [EPPlus Font Family Not Affected](https://stackoverflow.com/questions/40032251/epplus-font-family-not-affected/40170340)
