### ISSUE TITLE
无法加载：System.Security.Cryptography.Native.so

### ISSUE THREAD

**Issue by nbaxp** [VahidN/EPPlus.Core#5]
引入EPPlus.Core后，部署到centos7报错：DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
不引入EPPlus.Core可以在publish文件夹中找到System.Security.Cryptography.Native.so。引入就找不到了。

**Comment by VahidN** [comment]
It's discussed here: https://github.com/dotnet/corefx/issues/9171

> you have a mix of the 1.0 shared framework and a new 1.1-based individual package. The easiest answer is to **upgrade to 1.1**.
