### ISSUE TITLE
Runtime error: Could not load type System.StringExtensions from assembly CoreCompat.System.Drawing

### ISSUE THREAD

**Issue by Myrmex** [VahidN/EPPlus.Core#7]
Hi, I'm trying to migrate an existing DLL using EPPlus 4.1.0 to .NET Core, thus replacing the reference to EPPlus with that to this port. At compile time I have no issues, but when _consuming_ the library from a .NET 4.6.2 (WPF) application, I get this error when trying to create an Excel file:

> could not load type System.StringExtensions from assembly CoreCompat.System.Drawing

Googling around, I found this post which seems related: https://github.com/dotnet/corefx/issues/15471. It seems that there is no viable solution to the issue right now. Is this correct? Should I just wait for a later release? Thanks you!

**Comment by VahidN** [comment]
Added .NET 4.x support too. [Try V1.3.1](https://www.nuget.org/packages/EPPlus.Core)
![epppp](https://cloud.githubusercontent.com/assets/766010/23581034/1d3ac6b2-0122-11e7-9a2f-fd81ae69b87b.png)
