### ISSUE TITLE
Save as PDF?

### ISSUE THREAD

**Issue by MaximCrabbe** [VahidN/EPPlus.Core#8]
Hello,

Is it possible to save a xlsx file as a PDF file?
Been looking for this over weeks now for this feature in a .net core lib.
Thanks in advance.

**Comment by VahidN** [comment]
I have prepared a sample for the [PdfReport.Core](https://github.com/VahidN/PdfReport.Core) library to show how to use EPPlus.Core as a datasource: [ExcelToPdfReport](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs)
